name: Release-plz

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

env:
  CARGO_TERM_COLOR: always
  RELEASE_PLZ_VERSION: 0.3.159

jobs:
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    if: >-
      github.repository == 'salasebas/rustauth' &&
      (github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, 'chore: release') ||
      contains(github.event.head_commit.message, 'release-plz-'))
    environment: release
    permissions:
      contents: write
      id-token: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable

      - name: Run release-plz release
        uses: release-plz/action@e8792575c7f2366cf6ff3ccc33ead9ace5b691c7 # v0.5.130
        with:
          command: release
          version: ${{ env.RELEASE_PLZ_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    if: github.repository == 'salasebas/rustauth'
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-pr-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable

      - name: Run release-plz release-pr
        uses: release-plz/action@e8792575c7f2366cf6ff3ccc33ead9ace5b691c7 # v0.5.130
        with:
          command: release-pr
          version: ${{ env.RELEASE_PLZ_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
